# Pytorch Quickstart

https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

## Input Sample

In [1]:
import pandas as pd
import torch

data = {
    'feature1': [1.0, 2.0, 3.0, 4.0],
    'feature2': [5.0, 6.0, 7.0, 8.0],
    'feature3': [9.0, 10.0, 11.0, 12.0]
}

df = pd.DataFrame(data)
print("DataFrame:\n", df)

numpy_array = df.values
print("NumPy Array:\n", numpy_array)

tensor = torch.tensor(numpy_array, dtype=torch.float32)
print("PyTorch Tensor:\n", tensor)


DataFrame:
    feature1  feature2  feature3
0       1.0       5.0       9.0
1       2.0       6.0      10.0
2       3.0       7.0      11.0
3       4.0       8.0      12.0
NumPy Array:
 [[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
PyTorch Tensor:
 tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])


In [2]:
import torch

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8202, 0.9362, 0.3719],
        [0.4775, 0.7467, 0.3327],
        [0.3743, 0.6159, 0.1626],
        [0.6325, 0.2533, 0.3825],
        [0.5225, 0.7026, 0.3353]])


In [4]:
torch.cuda.is_available()

False

In [5]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [6]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="../../data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="../../data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [7]:
training_data

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: ../../data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [8]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [9]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

# Step 1: Create a sample DataFrame
data = {
    'feature1': [1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0, 4.0],
    'feature2': [5.0, 6.0, 7.0, 8.0, 5.0, 6.0, 7.0, 8.0],
    'feature3': [9.0, 10.0, 11.0, 12.0, 9.0, 10.0, 11.0, 12.0],
    'feature4': [9.0, 10.0, 11.0, 12.0, 9.0, 10.0, 11.0, 12.0],
    'label': [0., 1., 0., 1., 0.2, 0.8, 0.1, 0.9]
}

test_data = {
    'feature1': [1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0, 4.0],
    'feature2': [5.0, 6.0, 7.0, 8.0, 5.0, 6.0, 7.0, 8.0],
    'feature3': [9.0, 10.0, 11.0, 12.0, 9.0, 10.0, 11.0, 12.0],
    'feature4': [9.0, 10.0, 11.0, 12.0, 9.0, 10.0, 11.0, 12.0],
    'label': [0.1, .9, 0.2, .8, 0.2, 0.8, 0.1, 0.9]
}

# Step 2: Define a custom dataset class
class CustomDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe
        self.features = torch.tensor(dataframe.iloc[:, :-1].values, dtype=torch.float32)  # Assuming last column is the label
        self.labels = torch.tensor(dataframe.iloc[:, -1].values, dtype=torch.float32)  # Assuming labels are integers

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

# Step 3: Create an instance of the dataset and DataLoader
batch_size = 4  # Define your batch size

dataset = CustomDataset(df)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
train_dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
test_dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Step 4: Iterate through the DataLoader and check the batches
for batch_features, batch_labels in dataloader:
    print("Batch features:\n", batch_features)
    print("Batch labels:\n", batch_labels)


Batch features:
 tensor([[1., 5.],
        [3., 7.],
        [2., 6.],
        [4., 8.]])
Batch labels:
 tensor([ 9., 11., 10., 12.])


## Create Models

In [10]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")


# Define the neural network architecture
class NeuralNetwork(nn.Module):
    def __init__(self, input_size=4, hidden_size=4):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.output = nn.Linear(hidden_size, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.output(x)
        return x

# class DistNeuralNetwork(nn.Module):
#     def __init__(self, input_size, hidden_size):
#         super(NeuralNetwork, self).__init__()
#         self.fc1 = nn.Linear(input_size, hidden_size)
#         self.fc2 = nn.Linear(hidden_size, hidden_size)
#         self.mean = nn.Linear(hidden_size, 1)
#         self.log_var = nn.Linear(hidden_size, 1)
#         self.relu = nn.ReLU()

#     def forward(self, x):
#         x = self.relu(self.fc1(x))
#         x = self.relu(self.fc2(x))
#         return x

model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (fc1): Linear(in_features=4, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=4, bias=True)
  (output): Linear(in_features=4, out_features=1, bias=True)
  (relu): ReLU()
)


### Optimizing the Model Parameters

In [11]:
kl_loss = nn.KLDivLoss(reduction='batchmean')
mse_loss = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [12]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        outputs = model(X)
        # Apply LogSoftmax to the outputs
        # log_outputs = torch.log_softmax(outputs, dim=1)
        # Calculate loss
        # outputs = torch.log_softmax(outputs, dim=1)
        # y = torch.softmax(y, dim=1)

        loss = loss_fn(outputs, y)
        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [13]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            
            # pred = torch.log_softmax(pred, dim=1)
            # y = torch.softmax(y, dim=1)

            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


In [14]:

def eval(dataloader, model):
    model.eval()
    with torch.no_grad():
        for batch_features, batch_targets in dataloader:
            pred = model(batch_features)
            pred.view(-1)
            pred = torch.log(torch.abs(pred))
            # pred = torch.log(pred)
            # predicted, actual = classes[pred[0].argmax(0)], classes[y]
            print(f'Predicted: "{pred}", Actual: "{batch_targets}"')

In [15]:
epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, mse_loss, optimizer)
    test(test_dataloader, model, mse_loss)
print("Done!")

Epoch 1
-------------------------------


RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x2 and 4x4)

In [ ]:
eval(test_dataloader, model)

### Model Save & Load

In [ ]:
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

In [ ]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

In [ ]:
# classes = [
#     "T-shirt/top",
#     "Trouser",
#     "Pullover",
#     "Dress",
#     "Coat",
#     "Sandal",
#     "Shirt",
#     "Sneaker",
#     "Bag",
#     "Ankle boot",
# ]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    for batch_features, batch_targets in val_dataloader:
        mean, log_var = model(batch_features)
        predictions = mean
    pred, actual = model(x), y
    print(f'pred: "{pred}"')
    # predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{pred}", Actual: "{actual}"')